---
# Redhat 8 LAMP Stack
# Author: Arockiasamy K
# Version: 1.0

- name: Apply for common configuration to all the nodes
  hosts: all
  remote_user: ansible

  roles:
   - common
   
- name: deploy MySQL and configure databases
  hosts: dbservers
  remote_user: ansible
   
  roles:
   - db
   
- name: deploy Apache, PHP and configure website code
  hosts: webservers
  remote_user: ansible
   
  roles:
   - web
